# -*- coding: utf-8 -*-
"""Session 1 skills — HFT Foundations & Market Microstructure (deck U1, labs/session01.md)."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("trading.lob", "trading", "The central limit order book",
      "You can read a two-sided limit order book and compute the spread, mid, microprice and order-book imbalance from the top-of-book prices and sizes.",
      1, [], 3,
      [deck(1, "slides 10–12"),
       lab(1, "step 4 and the hand-computed book in Your turn"),
       hw(1),
       final("sys")], True),
    S("trading.price-time-priority", "trading", "Price-time priority & the FIFO queue",
      "You can apply price-then-time priority to say which resting order fills first, and explain why a cancel-and-repost sends you to the back of the queue.",
      1, [8, 9], 3,
      [deck(1, "slide 11"),
       deck(8, "slide 17"),
       lab(9, "Step 3 — self-cross bound and duplicate check"),
       hw(1),
       final("sys")], True),
    S("trading.tick-to-trade", "trading", "Tick-to-trade latency & the tail",
      "You can define tick-to-trade latency, report it as p50/p99/p99.9 instead of a mean, and explain why the tail is what decides an HFT race.",
      1, [], 3,
      [deck(1, "slides 13, 19"),
       lab(1, "step 3 — the tick->order latency print"),
       proj(0),
       final("meas")], True),
    S("trading.fees-maker-taker", "trading", "Maker/taker fees & rebates",
      "You can work out whether a fill was actually profitable once the taker fee or maker rebate is applied to the notional.",
      1, [], 2,
      [deck(1, "slide 12"),
       lab(1, "step 3 — the FEE_SCHEDULE line")]),
    S("trading.colocation", "trading", "Colocation & the latency arms race",
      "You can explain what colocation buys and weigh a reduced venue latency tier against its cost using measured percentiles.",
      1, [], 2,
      [deck(1, "slides 8, 14"),
       proj(0)]),
    S("tools.cmake-build", "tools", "Building a C++ project with CMake",
      "You can configure and build a C++ target with CMake and keep one build directory per flag set, so a cached flag never lies to you about what you measured.",
      1, [], 2,
      [deck(1, "slide 20"),
       lab(1, "step 2 — build the arena C++ client"),
       proj(0)]),
    S("tools.arena-client", "tools", "Writing a bot on the arena C++ client",
      "You can subclass the arena WebSocket bot client, override on_book/on_fill/on_ack, and place or cancel orders from the hot path.",
      1, [], 2,
      [deck(1, "slides 17–18"),
       lab(1, "step 3 — connect and get on the board"),
       proj(0)]),
    S("tools.replay-harness", "tools", "Offline replay & percentile reporting",
      "You can replay a recorded tape through your bot offline and read the p50/p99/p99.9 table it prints, so an A/B change is measured rather than guessed.",
      1, [], 3,
      [deck(1, "slide 19"),
       proj(0),
       final("meas")]),
]
