# -*- coding: utf-8 -*-
"""Session 2 skills — Pointers & the Cost of Memory + Object-Oriented C++ I
(Encapsulation & Inheritance). Deck U2, labs/session02.md (the old Sessions 2 and 3 MERGED
on 2026-10-05; skills merged to fit the 5-10 cap: pass-by-reference into pointers,
operator-overloading into classes-invariants, move-semantics into rule-of-five,
contiguous-layout + cache-line-alignment + object-layout into data-layout).

Deck slide numbers cite the merged u2 (69 slides): Part 1 = slides 4-36, Part 2 = slides 38-67."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("perf.memory-hierarchy", "perf", "The memory hierarchy, stack vs heap & storage duration",
      "You can put rough numbers on a register, L1, L2, L3 and DRAM access, explain why the stack is a nearly free bump pointer while the heap is a call into a service, and say which of the four storage durations a variable has.",
      2, [], 3,
      [deck(2, "slides 5–7"),
       lab(2, "Lab A — stack vs heap, sink the pointer"),
       midterm("cx"),
       final("cache")], True),
    S("cpp.pointers", "cpp", "Pointers, references & the cost of a copy",
      "You can walk an array with a raw pointer, read a const-qualified declaration right to left, explain where array decay loses the length, choose between a pointer and a reference by asking whether 'absent' is a legal answer, and default to const& for anything bigger than two words so a large struct is not copied on every call.",
      2, [], 3,
      [deck(2, "slides 9–15"),
       lab(2, "Lab A — pointers, const and decay: read the errors; run starters/hw02 as shipped"),
       hw(2),
       midterm("ptr")], True),
    S("cpp.raw-allocation", "cpp", "malloc / calloc / new / delete, the classic bugs & allocator non-determinism",
      "You can pair every malloc/calloc with free, every new with delete and every new[] with delete[], name the five classic heap bugs, and explain why the same allocation can take 12 ns or microseconds and land in p99.9.",
      2, [], 3,
      [deck(2, "slides 17–19, 23, 25–26, 46–47"),
       lab(2, "Lab A — memory bugs under a sanitizer"),
       hw(2),
       midterm("raii"),
       final("sys")], True),
    S("perf.data-layout", "perf", "Data layout & locality: contiguous blocks, SoA, padding, the 64-byte line & false sharing",
      "You can replace a double** matrix with one contiguous block and keep the inner loop on the contiguous axis, choose a struct-of-arrays layout so a hot scan streams whole cache lines, predict sizeof and alignof and reorder fields widest-first, and use alignas(64) so two cores never fight over one line.",
      2, [6], 3,
      [deck(2, "slides 20–22, 28–30, 54, 57"),
       deck(6, "slide 20"),
       lab(2, "Lab A — contiguous vs pointer chase, false sharing and alignas(64); Lab B — layout: sizeof, padding, static_assert"),
       hw(2),
       midterm("cx"),
       final("cache")], True),
    S("tools.sanitizers", "tools", "Finding bugs with ASan, UBSan, leaks & ThreadSanitizer",
      "You can build a -O0 -g binary with AddressSanitizer (and UBSan, or ThreadSanitizer for a threaded one), read the report down to the offending line, find a leak with LSan on Linux or leaks --atExit on macOS, and treat a clean run as evidence about one input rather than proof.",
      2, [6], 3,
      [deck(2, "slides 23–24"),
       deck(6, "slide 6"),
       lab(2, "Lab A — memory bugs under a sanitizer"),
       lab(6, "part A — the race under TSan"),
       final("meas")]),
    S("tools.benchmarking", "tools", "Honest micro-benchmarking & percentiles",
      "You can time a hot function with steady_clock in a -O2 build, warm up first, sink the result so the optimiser cannot delete the work, batch tiny operations, and report p50/p99/p99.9 with your machine stated rather than one mean.",
      2, [], 3,
      [deck(2, "slides 32–34"),
       lab(2, "Lab A — an honest micro-benchmark, and a dishonest one"),
       hw(2),
       proj(0),
       final("meas")], True),
    S("cpp.classes-invariants", "cpp", "Classes, access control, invariants & operators",
      "You can write a class whose private data is checked once in the constructor, initialise members in declaration order with explicit one-argument constructors and const observers, and overload only the operators whose meaning is obvious.",
      2, [], 3,
      [deck(2, "slides 39–44, 53"),
       lab(2, "Lab B — Order: an invariant, const, private data"),
       hw(2),
       midterm("oop"),
       final("core")], True),
    S("cpp.rule-of-five", "cpp", "Copy & move semantics: the Rule of Three, Five and Zero",
      "You can say when the compiler's member-by-member copy is right and when it is a double free, write a deep-copying, self-assignment-safe copy and a noexcept move that steals and blanks the source, explain why vector copies every element on growth when the move can throw, and pick between the Rule of Zero, the Rule of Five and = delete.",
      2, [3], 3,
      [deck(2, "slides 46–51"),
       deck(3, "slide 25"),
       lab(2, "Lab B — PxBuf: the Rule of Three and the double free under ASan; Rule of Five: noexcept and vector growth"),
       hw(2),
       midterm("raii"),
       final("core")], True),
    S("cpp.raii", "cpp", "RAII — scope-bound resource management",
      "You can wrap a resource in a type that acquires in its constructor and releases in its destructor, delete its copies so it has one owner, and rely on reverse-order destruction for cleanup on every exit path including a throw.",
      2, [3], 3,
      [deck(2, "slides 43, 55–56"),
       deck(3, "slide 23"),
       lab(2, "Lab B — ScopedTimer: RAII on every exit path"),
       hw(2),
       midterm("raii"),
       final("core")], True),
    S("cpp.inheritance", "cpp", "Inheritance without virtual: access, construction order, slicing & hiding",
      "You can state the construction and destruction order of a derived object with members, choose public inheritance only for a true is-a and composition otherwise, spot slicing when a derived object is copied into a base by value, and explain how a derived name hides every base overload.",
      2, [3], 3,
      [deck(2, "slides 59–65"),
       deck(3, "slides 5, 7"),
       lab(2, "Lab B — construction order; slicing, name hiding, static binding"),
       hw(2),
       midterm("oop"),
       final("core")], True),
]
