# -*- coding: utf-8 -*-
"""Session 2 skills — Pointers & the Cost of Memory (deck U2, labs/session02.md)."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("perf.memory-hierarchy", "perf", "The memory hierarchy, stack vs heap & storage duration",
      "You can put rough numbers on a register, L1, L2, L3 and DRAM access, explain why the stack is a nearly free bump pointer while the heap is a call into a service, and say which of the four storage durations a variable has.",
      2, [], 3,
      [deck(2, "slides 5–7"),
       lab(2, "step 3 — stack vs heap, sink the pointer"),
       midterm("cx"), final("cache")], True),
    S("cpp.pointers", "cpp", "Pointers, references & pointer arithmetic",
      "You can walk an array with a raw pointer, read a const-qualified pointer declaration right to left, explain why p + 1 advances by sizeof(*p) and where array decay loses the length, and choose between a pointer and a reference by asking whether 'absent' is a legal answer.",
      2, [], 3,
      [deck(2, "slides 9–14"),
       lab(2, "step 2 — pointers, const and decay: read the errors"),
       hw(2), midterm("ptr")], True),
    S("cpp.pass-by-reference", "cpp", "The cost of a copy: by value vs const&",
      "You can predict what passing a large struct by value costs, default to const& for anything bigger than two words, keep small types by value, and build a benchmark the optimiser cannot elide the copy out of.",
      2, [], 3,
      [deck(2, "slide 15"),
       lab(2, "step 7 — run starters/hw02 as shipped"),
       hw(2), midterm("ptr")], True),
    S("cpp.raw-allocation", "cpp", "malloc / calloc / new / delete, the classic bugs & allocator non-determinism",
      "You can pair every malloc/calloc with free, every new with delete and every new[] with delete[], name the five classic heap bugs, and explain why the same allocation can take 12 ns or microseconds and land in p99.9.",
      2, [3], 3,
      [deck(2, "slides 17–19, 23, 25–26"), deck(3, "slides 12–13"),
       lab(2, "step 5 — memory bugs under a sanitizer"),
       hw(3), midterm("raii"), final("sys")], True),
    S("perf.contiguous-layout", "perf", "Contiguous layout: one-block matrices, row-major order & SoA",
      "You can replace a double** matrix with one contiguous block indexed r*cols + c, keep the inner loop on the contiguous axis, and choose a struct-of-arrays layout so a hot scan streams whole cache lines instead of chasing pointers.",
      2, [], 3,
      [deck(2, "slides 20–22, 29"),
       lab(2, "step 4 — contiguous vs pointer chase; row- vs column-major"),
       hw(2), midterm("cx"), final("cache")], True),
    S("tools.sanitizers", "tools", "Finding bugs with ASan, UBSan, leaks & ThreadSanitizer",
      "You can build a -O0 -g binary with AddressSanitizer (and UBSan, or ThreadSanitizer for a threaded one), read the report down to the offending line, find a leak with LSan on Linux or leaks --atExit on macOS, and treat a clean run as evidence about one input rather than proof.",
      2, [7], 3,
      [deck(2, "slides 23–24"), deck(7, "slide 6"),
       lab(2, "step 5 — memory bugs under a sanitizer"), lab(7, "part A — the race under TSan"),
       final("meas")]),
    S("perf.cache-line-alignment", "perf", "The 64-byte cache line, alignment & false sharing",
      "You can pack the fields a hot function reads onto one 64-byte cache line, use alignas to stop a hot object straddling two of them, and recognise false sharing from a threaded version being slower than a single-threaded one.",
      2, [7], 3,
      [deck(2, "slides 28, 30"), deck(7, "slide 20"),
       lab(2, "step 6 — false sharing and alignas(64)"),
       midterm("cx"), final("cache")], True),
    S("tools.benchmarking", "tools", "Honest micro-benchmarking & percentiles",
      "You can time a hot function with steady_clock in a -O2 build, warm up first, sink the result so the optimiser cannot delete the work, batch tiny operations, and report p50/p99/p99.9 with your machine stated rather than one mean.",
      2, [], 3,
      [deck(2, "slides 32–34"),
       lab(2, "step 1 — an honest micro-benchmark, and a dishonest one"),
       hw(2), proj(0), final("meas")], True),
]
