# -*- coding: utf-8 -*-
"""Session 3 skills — Object-Oriented C++ I: Encapsulation & Inheritance
(deck U3, labs/session03.md)."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("cpp.classes-invariants", "cpp", "Classes, access control & invariants",
      "You can write a class whose private data is checked once in the constructor, initialise members in the member-initialiser list in declaration order, mark one-argument constructors explicit, and make every observer a const member function.",
      3, [], 3,
      [deck(3, "slides 5–10"),
       lab(3, "step 1 — Order: an invariant, const, private data"),
       hw(3), midterm("oop"), final("core")], True),
    S("cpp.rule-of-five", "cpp", "Copy semantics & the Rule of Three / Five / Zero",
      "You can say when the compiler's member-by-member copy is right and when it is a double free, write a deep-copying, self-assignment-safe copy constructor and copy assignment, and pick between the Rule of Zero, the Rule of Five and = delete for a given type.",
      3, [], 3,
      [deck(3, "slides 12–13, 17"),
       lab(3, "step 3 — PxBuf: the Rule of Three, and the double free under ASan"),
       hw(3), midterm("raii"), final("core")], True),
    S("cpp.move-semantics", "cpp", "lvalues, rvalues, std::move & noexcept moves",
      "You can tell an lvalue from an rvalue, say that std::move is only a cast, write a noexcept move constructor that steals and then blanks the source, and explain why vector copies every element on growth when the move is not noexcept.",
      3, [4], 3,
      [deck(3, "slides 14–16"), deck(4, "slide 25"),
       lab(3, "step 4 — Rule of Five: noexcept and vector growth"),
       hw(3), midterm("raii"), final("core")], True),
    S("cpp.raii", "cpp", "RAII — scope-bound resource management",
      "You can wrap a resource in a type that acquires in its constructor and releases in its destructor, delete its copies so it has one owner, and rely on reverse-order destruction for cleanup on every exit path including a throw.",
      3, [4], 3,
      [deck(3, "slides 9, 21–22"), deck(4, "slide 23"),
       lab(3, "step 5 — ScopedTimer: RAII on every exit path"),
       hw(3), midterm("raii"), final("core")], True),
    S("cpp.operator-overloading", "cpp", "Operator overloading — the useful subset",
      "You can overload operator==, operator< (or default operator<=>), operator() and a free operator<< where their meaning is obvious, so sort, containers and algorithms pick your type up, and name a function everywhere else.",
      3, [], 1,
      [deck(3, "slide 19"), final("core")]),
    S("perf.object-layout", "perf", "Object layout: sizeof, padding & member order",
      "You can predict a struct's sizeof and alignof from its members, reorder fields widest-first to remove padding, and static_assert the size and trivial copyability of a hot-path type so a stray std::string breaks the build.",
      3, [], 3,
      [deck(3, "slides 20, 23"),
       lab(3, "step 6 — layout: sizeof, padding, static_assert"),
       hw(3), midterm("cx"), final("cache")], True),
    S("cpp.inheritance", "cpp", "Inheritance without virtual: access, construction order, slicing & hiding",
      "You can state the construction and destruction order of a derived object with members, choose public inheritance only for a true is-a and composition otherwise, spot slicing when a derived object is copied into a base by value, and explain how a derived name hides every base overload.",
      3, [4], 3,
      [deck(3, "slides 25–31"), deck(4, "slides 5, 7"),
       lab(3, "steps 2 and 7 — construction order; slicing, name hiding, static binding"),
       hw(3), midterm("oop"), final("core")], True),
]
