# -*- coding: utf-8 -*-
"""Session 4 skills — Templates, Compile-Time & CRTP (deck U4, labs/session04.md). The midterm (Oct 26) covers Sessions 1-4, so these carry the Templates group."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("cpp.templates", "cpp", "Function & class templates",
      "You can write a function or class template with a type and a non-type parameter, let the compiler deduce its arguments, specialise the one type that deserves hand-tuning, and say why templates live in headers and what every extra instantiation costs in code size.",
      4, [5], 3,
      [deck(4, "slides 5–7"),
       deck(5, "slide 10"),
       lab(4, "steps 1–2 — Ring<T, N>, two deliberate compile errors, Wire<T> specializations"),
       hw(4),
       final("tpl"),
       midterm("tpl")], True),
    S("cpp.variadic-templates", "cpp", "Parameter packs, folds & perfect forwarding",
      "You can write a variadic template that folds over its pack in one line, forward every argument unchanged with std::forward, and build the overload{} visitor from a pack of lambdas.",
      4, [], 3,
      [deck(4, "slides 9–10"),
       lab(4, "step 3 — folds, if constexpr and the overload{} visitor"),
       hw(4),
       final("tpl")]),
    S("cpp.type-traits-constraints", "cpp", "Type traits, concepts & if constexpr",
      "You can ask the compiler questions about a type with <type_traits>, constrain a template with a C++20 concept instead of SFINAE so the error names the failed requirement, and give one template a separate code path per type with if constexpr.",
      4, [], 3,
      [deck(4, "slides 11–13"),
       lab(4, "steps 3–4 — if constexpr, then SFINAE next to a concept"),
       hw(4),
       final("tpl"),
       midterm("tpl")], True),
    S("cpp.constexpr", "cpp", "constexpr, consteval & static_assert",
      "You can move a table or a constant into the compiler with constexpr, force compile-time evaluation with consteval, and park every size, fee and layout assumption in a static_assert so a violation fails the build instead of the market.",
      4, [], 3,
      [deck(4, "slide 15"),
       lab(4, "step 5 — consteval fees and a compile-time tick table"),
       hw(4),
       final("tpl"),
       midterm("tpl")], True),
    S("cpp.crtp-policies", "cpp", "CRTP & policy-based design",
      "You can replace a virtual hook with a CRTP base that calls down through static_cast, show with dispatch_bench and the -O2 assembly that the indirect branch is gone, and assemble a class from policy template parameters.",
      4, [], 3,
      [deck(4, "slides 16–18"),
       lab(4, "steps 6–7 — the CRTP row in dispatch_bench, then a policy-based Quoter"),
       hw(4),
       final("tpl"),
       midterm("tpl")], True),
]
