# -*- coding: utf-8 -*-
"""Session 6 skills — Concurrency: From Atomics to Lock-Free (deck U6, labs/session06.md)."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("cpp.data-races", "cpp", "std::thread, data races & happens-before",
      "You can start and join threads, identify a data race as undefined behaviour rather than merely a wrong value, and name the happens-before edge — a mutex, an atomic, or thread start and join — that would make the access legal.",
      6, [], 3,
      [deck(6, "slides 5–7"),
       lab(6, "Part A, steps A1–A4 — the race at -O0 and -O2, TSan, the volatile non-fix, the atomic fix"),
       final("thr")], True),
    S("cpp.atomics-memory-order", "cpp", "std::atomic & memory ordering",
      "You can choose relaxed, acquire/release or seq_cst for each atomic operation, justify it with the happens-before edge you actually need, and explain why the store-buffer litmus test needs seq_cst.",
      6, [9], 3,
      [deck(6, "slides 9–12"),
       lab(6, "Part B, steps B1–B3 — the release/acquire handoff, -DBROKEN under TSan, the litmus test"),
       lab(9, "Step 5 — the kill switch, with its automatic trips"),
       hw(6),
       final("atom")], True),
    S("perf.lock-tail-cost", "perf", "Why a lock on the hot path is a tail bomb",
      "You can take a mutex correctly through a lock_guard, then show from a measured p50/p99.9 table how a contended one wins the median and loses the tail to a futex wait, a context switch or a priority inversion.",
      6, [], 3,
      [deck(6, "slides 14–15"),
       lab(6, "step A5 — mutex vs atomic vs private in lock_tail.cpp"),
       final("thr")], True),
    S("cpp.compare-and-swap", "cpp", "Compare-and-swap, ABA & progress guarantees",
      "You can write a compare_exchange retry loop that recomputes the desired value on every attempt, explain the ABA problem as a memory-reclamation problem, and place a structure on the wait-free / lock-free / obstruction-free ladder.",
      6, [], 3,
      [deck(6, "slides 16–17, 35"),
       final("atom")], True),
    S("perf.spsc-ring", "perf", "A lock-free SPSC ring buffer",
      "You can build a bounded single-producer/single-consumer ring with monotonic head and tail counters, a power-of-two mask, a release store that publishes each slot and the two indices on separate cache lines — and say which two lines make it correct.",
      6, [], 3,
      [deck(6, "slides 19–20, 22"),
       lab(6, "Part C, steps C1–C6 — push(), then pop()/empty()/full() yourself, make spsc-conc and spsc-tsan"),
       hw(6),
       proj(3),
       final("atom")], True),
    S("perf.back-pressure", "perf", "Bounded queues & back-pressure",
      "You can make a full queue a decision — drop, coalesce or shed, and count it — instead of a stall on the socket thread, and explain how head-of-line blocking turns one fat message into a tail.",
      6, [], 3,
      [deck(6, "slides 21, 28"),
       lab(6, "step E2 — wire the ring into your bot, drop and count"),
       proj(3),
       final("atom")]),
    S("perf.shared-memory-ring", "perf", "A shared-memory ring across processes",
      "You can put a lock-free POD ring in a shm_open/mmap region so two processes hand messages over without a syscall, and say why it may hold no pointers, no owning containers and only always-lock-free atomics.",
      6, [], 3,
      [deck(6, "slides 24–25"),
       lab(6, "Part D, steps D1–D3 — ShmRing, the fork() test, shm_pipeline.cpp"),
       proj(4),
       final("atom")]),
    S("cpp.cpp20-coordination", "cpp", "C++20 coordination primitives",
      "You can line threads up with a std::latch, park an idle thread on atomic::wait/notify instead of a condition variable, and shut a std::jthread down cooperatively with its stop_token.",
      6, [], 2,
      [deck(6, "slide 26"),
       final("thr")]),
]
