# -*- coding: utf-8 -*-
"""Session 6 skills — memory pools & the order book (deck U6, labs/session06.md)."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("perf.object-pool", "perf", "Fixed-size object pools",
      "You can implement a fixed-size object pool whose free slots hold the free-list, so allocate and free are O(1) pointer swaps that never call the system allocator, and defend its number as stable rather than merely small.",
      6, [], 3,
      [deck(6, "slides 5–6, 8–10, 13"),
       lab(6, "Part A — steps A2–A6, all four pool tests green"),
       hw(6), proj(2), final("sys")], True),
    S("cpp.placement-new", "cpp", "Placement new & explicit destruction",
      "You can construct an object into aligned storage you already own with placement new, end its life with an explicit destructor call, and hand the slot back to the pool — never to delete.",
      6, [], 2,
      [deck(6, "slides 7, 9"),
       lab(6, "step A5 — placement new + explicit destructor through your pool"),
       hw(6), final("core")], True),
    S("perf.arena-allocator", "perf", "Arena (bump) allocation & std::pmr",
      "You can allocate a tick's scratch from a bump pointer over a pre-owned slab, align each request, reclaim everything with one O(1) reset, and get the same from std::pmr::monotonic_buffer_resource with a null upstream.",
      6, [], 2,
      [deck(6, "slides 11–12, 34"),
       lab(6, "step D1 — a bump allocator with reset(), timed against the pool"),
       final("sys")]),
    S("cpp.stl-containers", "cpp", "Choosing a container for an access pattern",
      "You can match ordered traversal, best-element access and point lookup to a tree, a heap and a hash table, and say what each costs in allocations and cache misses rather than only in big-O.",
      6, [], 2,
      [deck(6, "slides 15, 17"),
       lab(6, "step B1 — why not std::map<double, Level>?"),
       final("tpl")]),
    S("perf.open-addressing-hash", "perf", "Open-addressing hash maps",
      "You can implement a linear-probing hash map in one flat power-of-two array, keep its load factor under about 0.7, and explain why it beats std::unordered_map's chained heap nodes on a hot path.",
      6, [], 3,
      [deck(6, "slides 16, 23"),
       lab(6, "step B7 — SymMap: open addressing, no per-lookup allocation"),
       hw(6), proj(2), final("sys")], True),
    S("trading.flat-order-book", "trading", "A flat, price-indexed local order book",
      "You can hold a book as a price-indexed band of tick slots against a base tick with a cached touch, bounds-check both ends, and explain why an absolute index silently corrupts the other side for a $720 name.",
      6, [], 3,
      [deck(6, "slides 17–20, 23"),
       lab(6, "steps B2–B6, then the NFLX band test in step D2"),
       hw(6), proj(2), final("sys")], True),
    S("trading.queue-position", "trading", "FIFO per level & your queue position",
      "You can keep each price level as an O(1) intrusive FIFO of pooled orders, track your queue_ahead from on_ack / on_queue, and explain why a reprice sends you to the back.",
      6, [9], 3,
      [deck(6, "slides 21–22"), deck(9, "slide 17"),
       proj(2), final("sys")], True),
    S("perf.complexity-in-cache-terms", "perf", "Complexity counted in cache misses",
      "You can explain why an O(n) scan of a small contiguous array beats an O(log n) tree, treat amortized O(1) as a worst-case tail event that reserve() removes, and measure the crossover on your own machine.",
      6, [], 3,
      [deck(6, "slides 25, 37"),
       lab(6, "Part C — make bench-alloc and make bench-book on your machine"),
       final("tpl")], True),
    S("perf.incremental-computation", "perf", "Ring buffers & O(1) online statistics",
      "You can keep the recent tape in a power-of-two ring buffer and fold each tick into a running mean, Welford variance and EMA in O(1), so the signal costs the same on every tick.",
      6, [], 3,
      [deck(6, "slides 26–27, 35"),
       lab(6, "step D3 — the ring buffer and Welford, checked by hand"),
       proj(2), final("sys")]),
]
