# -*- coding: utf-8 -*-
"""Session 7 skills — The Wire & the Machine (deck U7, labs/session07.md)."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("trading.fix-protocol", "trading", "Parsing FIX tag=value messages",
      "You can pull the fields you need out of a SOH-delimited FIX message in one forward scan without allocating, keep the ClOrdID as a view, and reject the message on a bad mod-256 checksum.",
      7, [], 3,
      [deck(7, "slides 5, 29"),
       lab(7, "step 1 — the single-pass FIX parser (make fix)"),
       hw(7),
       final("net")], True),
    S("trading.binary-market-data", "trading", "Fixed-width binary market data",
      "You can decode an ITCH/OUCH-style fixed-width message by memcpy-ing fields from known offsets, byte-swapping from network order and keeping prices as scaled integers, with a bounds check first and no digit parsing.",
      7, [], 3,
      [deck(7, "slides 6, 27"),
       final("net")]),
    S("trading.feed-sequencing", "trading", "TCP vs UDP multicast, sequence numbers & gap fill",
      "You can say why order entry runs over TCP and market data over UDP multicast, track the next expected sequence number to drop A/B duplicates and detect a gap, and keep a symbol untradeable until snapshot-plus-increment recovery completes.",
      7, [], 2,
      [deck(7, "slides 7–8"),
       final("net")]),
    S("tools.message-framing", "tools", "Framing a byte stream into messages",
      "You can recover message boundaries from a TCP byte stream with a length prefix or FIX BodyLength, dispatch complete frames as views, keep the partial remainder, and validate a length against a maximum before you trust it.",
      7, [], 3,
      [deck(7, "slide 9"),
       lab(7, "step 3 — frame a FIX stream by BodyLength and verify the checksum"),
       hw(7),
       final("net")]),
    S("perf.nonblocking-io", "perf", "Non-blocking I/O, readiness loops & batching vs latency",
      "You can drain a non-blocking socket until EAGAIN inside a poll/epoll/kqueue readiness loop, say what edge-triggered mode obliges you to do, and explain why batching and Nagle buy throughput at the cost of the tail — hence TCP_NODELAY on the order path.",
      7, [], 2,
      [deck(7, "slides 11–12, 15, 28"),
       lab(7, "step 3 — the O_NONBLOCK + poll() reader in frame_demo.cpp"),
       final("net")]),
    S("perf.zero-copy-parse", "perf", "Zero-copy parse & hand-rolled serialization",
      "You can extract only the three fields you need from a frame with a string_view instead of building a DOM, write digits into a reused buffer with no snprintf or std::string on the send path, and show the win on a replay tape.",
      7, [], 3,
      [deck(7, "slides 13–14, 16"),
       lab(7, "step 2 and take-home step 3 — u64toa, then the targeted extract in your bot"),
       hw(7),
       proj(5),
       final("net")], True),
    S("perf.simd", "perf", "The memory wall, SIMD & prefetch",
      "You can explain why a hot loop is memory-bound, let the compiler vectorize a reduction with -O3 -march=native and read its vectorization report to see why it refused, and issue a prefetch hint whose distance you tune by measurement.",
      7, [], 3,
      [deck(7, "slides 18–19"),
       lab(7, "step 4 and take-home step 2 — -O0 vs -O3, why 'not vectorized', AVX2 by hand"),
       proj(5),
       final("simd")], True),
    S("perf.kernel-bypass", "perf", "Syscalls, busy-poll & kernel bypass",
      "You can explain what a trip into the kernel costs on a hot path, when busy-polling a dedicated core beats being woken, and what DPDK, Onload/ef_vi, AF_XDP and io_uring each remove from the per-packet path.",
      7, [], 2,
      [deck(7, "slides 20, 28"),
       proj(5),
       final("net")], True),
    S("perf.cpu-pinning-numa", "perf", "Pinning, isolation, NUMA & huge pages",
      "You can pin a hot thread to an isolated core, explain that pinning buys variance rather than speed, keep memory on the NIC's NUMA node, and pre-fault and lock hot memory at startup so no page fault lands mid-race.",
      7, [], 2,
      [deck(7, "slides 21, 30"),
       lab(7, "take-home step 4 — pin the hot thread and compare the p99.9 spread"),
       proj(5),
       final("sys")]),
    S("perf.hardware-timestamping", "perf", "PTP, hardware timestamps, NICs & FPGAs",
      "You can explain why NTP is too coarse for microsecond work, what a NIC hardware timestamp measures that a user-space clock read cannot, and where an FPGA takes over from your C++.",
      7, [], 1,
      [deck(7, "slide 22"),
       final("meas")]),
]
