# -*- coding: utf-8 -*-
"""Session 9 skills — Pre-trade Risk & Controls (labs/session09.md, HW 9). NEW material,
added in the 2026-10-05 re-schedule. Practised here but defined elsewhere:
cpp.atomics-memory-order (sk6), trading.price-time-priority (sk1)."""
from skills_common import *  # noqa: F401,F403

SKILLS = [
    S("trading.order-size-notional-collar", "trading", "Pre-trade checks: max size, notional & the price collar",
      "You can reject an order before it leaves the process when its quantity breaks a max-order size, its price times quantity breaks a notional cap, or its price sits outside a collar around a reference price, and say why the collar is what catches a fat-finger limit order.",
      9, [], 3,
      [deck(9, "slides 10, 19"),
       lab(9, "Step 1 — size, notional, sanity, collar"),
       hw(9),
       proj(7),
       final("sys")], True),
    S("trading.position-exposure-limits", "trading", "Position & exposure limits: net, gross & resting orders",
      "You can track a signed net position and the gross exposure per symbol, count what is still resting as potential position, and reject the order whose worst-case fill would breach the limit rather than the one that already has.",
      9, [], 3,
      [deck(9, "slide 11"),
       lab(9, "Step 2 — position with open orders (on_fill / on_done)"),
       hw(9),
       proj(7),
       final("sys")], True),
    S("perf.token-bucket-throttle", "perf", "Rate limits: the token bucket",
      "You can write a token bucket that refills from a monotonic clock, allows a burst up to its capacity and a sustained rate beyond which orders are rejected, and keep the check to a few arithmetic operations with no clock read of its own, so it costs a few nanoseconds.",
      9, [], 3,
      [deck(9, "slide 12"),
       lab(9, "Step 4 — the token bucket"),
       hw(9),
       proj(7),
       final("sys")], True),
    S("cpp.atomic-kill-switch", "cpp", "An atomic kill switch on the hot path",
      "You can gate every outbound order on one std::atomic<bool> loaded with a relaxed or acquire load, flip it from another thread or a signal handler, and say why a flag rather than a lock or a message is what makes a kill switch both instant and nearly free.",
      9, [], 3,
      [deck(9, "slides 15, 21"),
       lab(9, "Step 5 — the kill switch, with its automatic trips"),
       hw(9),
       proj(7),
       final("atom")], True),
    S("trading.self-trade-prevention", "trading", "Self-trade prevention",
      "You can detect that an incoming order would cross your own resting order, choose between cancel-newest, cancel-resting and reject, and explain why a wash trade is a compliance problem and not just wasted fees.",
      9, [], 2,
      [deck(9, "slides 13–14"),
       lab(9, "Step 3 — self-cross bound and duplicate check"),
       hw(9),
       final("sys")], True),
    S("perf.risk-check-cost", "perf", "What a risk check costs: nanoseconds, branches & cache",
      "You can order the checks cheapest and most likely to fail first, keep every limit in one cache-resident struct, measure the whole gate in nanoseconds per order with a sink and percentiles, and decide what a check is worth against the latency budget.",
      9, [], 3,
      [deck(9, "slides 18–20, 22"),
       lab(9, "Step 6 — what does it cost? (make risk-bench)"),
       hw(9),
       proj(7),
       final("meas")], True),
    S("trading.risk-regulation", "trading", "SEC Rule 15c3-5 & the Knight Capital lesson",
      "You can say what the SEC's market access rule requires of a firm that routes orders to an exchange — automated pre-trade controls under the firm's own control — and tell the Knight Capital 2012 story as a failure of deployment and of controls.",
      9, [], 2,
      [deck(9, "slides 5–8, 16, 23"),
       hw(9),
       final("sys")], True),
]
